In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.zeros((2,3)) #2*3 array of zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [25]:
L=np.eye(3)#Identity matrix 3*3
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [50]:
k=np.random.rand(3,2)#random value in [0,1)
k

array([[0.6662793 , 0.02362995],
       [0.3463409 , 0.11971695],
       [0.46017445, 0.01489728]])

In [28]:
np.random.randint(1,10,5)# 5 random integer from 1 to 9 

array([6, 8, 9, 6, 7])

In [23]:
L.shape#(rows,columns)

(3, 3)

In [24]:
L.ndim

2

In [29]:
k.ndim

2

In [31]:
L.size #total number of element

9

In [32]:
L.dtype

dtype('float64')

In [37]:
A=np.array([1,2,3,4,5,6])
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [39]:
A.T

array([1, 2, 3, 4, 5, 6])

In [40]:
A[1]

2

In [41]:
A[1:4]

array([2, 3, 4])

In [45]:
A[:-2]

array([1, 2, 3, 4])

In [47]:
A[1:]

array([2, 3, 4, 5, 6])

In [48]:
A[-1]

6

In [53]:
S=np.array([1,2,3,4,5,6,7,8,9])
s=S.reshape(3,3)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
L+s

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [55]:
L*s#elementwise

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [56]:
np.dot(L,s)#matrix multiplication

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [57]:
np.sum(L)#sum of elements

3.0

In [59]:
np.mean(L)

0.3333333333333333

In [60]:
np.std(L)

0.4714045207910317

In [61]:
np.max(L)

1.0

In [62]:
np.min(L)

0.0

In [63]:
np.argmax(L)#index of max

0

In [64]:
np.cumsum(L)#cumulative sum

array([1., 1., 1., 1., 2., 2., 2., 2., 3.])

In [65]:
L>5#elementwise comparison

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [66]:
L[L>=1]#Filter element >=5

array([1., 1., 1.])

In [74]:
np.where(L >= 1, 1, 0)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [75]:
np.any(L>0)

True

In [76]:
np.all(L>0)

False

In [77]:
np.vstack((L,s))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [78]:
np.hstack((L,s))

array([[1., 0., 0., 1., 2., 3.],
       [0., 1., 0., 4., 5., 6.],
       [0., 0., 1., 7., 8., 9.]])

In [79]:
np.concatenate([L,s],axis=0)#axis=0 means vertically ,axis = 1 means horizontally

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [80]:
np.concatenate([L,s],axis=1)

array([[1., 0., 0., 1., 2., 3.],
       [0., 1., 0., 4., 5., 6.],
       [0., 0., 1., 7., 8., 9.]])

In [81]:
s=L.copy()

In [82]:
s

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.save('data.npy',L)

In [84]:
np.load('data.npy')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.savetxt('data.csv',L,delimiter=',') #save as scv

In [93]:
np.genfromtxt('data.csv',delimiter=',')#load csv and separate by comma

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## PANDAS

In [94]:
import pandas as pd

In [99]:
Data = pd.DataFrame(
    {
        'PIN': ['4444','6776','9999','0000'],
        'ID': ['0001','0002','0003','0004'],
        'Name': ['joseline','branche','benoit','beatrice']
    }
)
Data

PIN    ID      Name
0  4444  0001  joseline
1  6776  0002   branche
2  9999  0003    benoit
3  0000  0004  beatrice

In [100]:
pd.DataFrame(np.random.rand(3,2),columns=['A','B'])

A         B
0  0.297678  0.648354
1  0.577470  0.111437
2  0.326612  0.061871

In [103]:
Data.to_csv('data.csv')#save to csv
Data.to_excel('data.xlsx')#to excel
Data.to_stata('data.dta')#stata
Data.to_json('data.json')#json

In [105]:
pd.read_csv('data.csv')

Unnamed: 0   PIN  ID      Name
0           0  4444   1  joseline
1           1  6776   2   branche
2           2  9999   3    benoit
3           3     0   4  beatrice

In [106]:
pd.read_excel('data.xlsx')

Unnamed: 0   PIN  ID      Name
0           0  4444   1  joseline
1           1  6776   2   branche
2           2  9999   3    benoit
3           3     0   4  beatrice

In [110]:
df = pd.DataFrame(np.random.rand(3,2),columns=['A','B'])

In [111]:
df

A         B
0  0.451836  0.536415
1  0.843290  0.061774
2  0.536053  0.507233

In [112]:
df.info()#summary description

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       3 non-null      float64
 1   B       3 non-null      float64
dtypes: float64(2)
memory usage: 180.0 bytes


In [113]:
df.describe()

A         B
count  3.000000  3.000000
mean   0.610393  0.368474
std    0.206043  0.266011
min    0.451836  0.061774
25%    0.493945  0.284503
50%    0.536053  0.507233
75%    0.689672  0.521824
max    0.843290  0.536415

In [114]:
df.shape

(3, 2)

In [115]:
df.columns

Index(['A', 'B'], dtype='object')