In [57]:
import pandas as pd
import numpy as np

In [58]:
age=np.array([10,20,30,40,50,60,70,80])
name=np.array(['alice','ange','bebe','alice','olive','alice','def','elie'])
df=pd.DataFrame({'age':age,'name':name})

In [59]:
df

age   name
0   10  alice
1   20   ange
2   30   bebe
3   40  alice
4   50  olive
5   60  alice
6   70    def
7   80   elie

In [60]:
df[df['age']>25]

age   name
2   30   bebe
3   40  alice
4   50  olive
5   60  alice
6   70    def
7   80   elie

In [61]:
df[df['name']=='alice']

age   name
0   10  alice
3   40  alice
5   60  alice

In [62]:
df[(df['age']>25) & (df['name']=='alice')]

age   name
3   40  alice
5   60  alice

In [63]:
df[(df['age']>20) | (df['age']>30)]

age   name
2   30   bebe
3   40  alice
4   50  olive
5   60  alice
6   70    def
7   80   elie

In [64]:
df['age']=df['age']+1

In [65]:
df

age   name
0   11  alice
1   21   ange
2   31   bebe
3   41  alice
4   51  olive
5   61  alice
6   71    def
7   81   elie

In [66]:
df['newcol']=df['age']*2

In [67]:
df

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [68]:
df.rename(columns={'newcol':'marks'})

age   name  marks
0   11  alice     22
1   21   ange     42
2   31   bebe     62
3   41  alice     82
4   51  olive    102
5   61  alice    122
6   71    def    142
7   81   elie    162

In [69]:
df.value_counts()

age  name   newcol
11   alice  22        1
21   ange   42        1
31   bebe   62        1
41   alice  82        1
51   olive  102       1
61   alice  122       1
71   def    142       1
81   elie   162       1
dtype: int64

In [13]:
df.drop('newcol',axis=1)

age   name
0   11  alice
1   21   ange
2   31   bebe
3   41  alice
4   51  olive
5   61  alice
6   71    def
7   81   elie

In [14]:
df.sort_values('age')

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [15]:
df.sort_values(['age'],ascending=False)

age   name  newcol
7   81   elie     162
6   71    def     142
5   61  alice     122
4   51  olive     102
3   41  alice      82
2   31   bebe      62
1   21   ange      42
0   11  alice      22

In [16]:
df.groupby('name').mean()#group by name and make mean of each 

age      newcol
name                        
alice  37.666667   75.333333
ange   21.000000   42.000000
bebe   31.000000   62.000000
def    71.000000  142.000000
elie   81.000000  162.000000
olive  51.000000  102.000000

In [17]:
df['name'].value_counts()#count unique value

alice    3
ange     1
bebe     1
olive    1
def      1
elie     1
Name: name, dtype: int64

In [18]:
df.isnull()

age   name  newcol
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False   False

In [19]:
df.dropna()

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [20]:
df.fillna(0)

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [21]:
df['age'].fillna(df['age'].mean())

0    11
1    21
2    31
3    41
4    51
5    61
6    71
7    81
Name: age, dtype: int64

In [22]:
df1 = pd.DataFrame({'key':['A','B','C'],'value1':[1,2,3]})

In [23]:
df2=pd.DataFrame({'key':['A','B','C'],'value2':[4,5,6]})

In [24]:
df1,df2

(  key  value1
 0   A       1
 1   B       2
 2   C       3,
   key  value2
 0   A       4
 1   B       5
 2   C       6)

In [25]:
pd.concat([df1,df2],axis=0)

key  value1  value2
0   A     1.0     NaN
1   B     2.0     NaN
2   C     3.0     NaN
0   A     NaN     4.0
1   B     NaN     5.0
2   C     NaN     6.0

In [26]:
pd.concat([df1,df2],axis=1)

key  value1 key  value2
0   A       1   A       4
1   B       2   B       5
2   C       3   C       6

In [27]:
pd.merge(df1,df2,on='key',how='inner')

key  value1  value2
0   A       1       4
1   B       2       5
2   C       3       6

In [28]:
pd.merge(df1,df2,on='key',how='left')

key  value1  value2
0   A       1       4
1   B       2       5
2   C       3       6

In [29]:
pd.merge(df1,df2,on='key',how='right')

key  value1  value2
0   A       1       4
1   B       2       5
2   C       3       6

In [30]:
df1.join(df2.set_index('key'),on='key',how='inner')

key  value1  value2
0   A       1       4
1   B       2       5
2   C       3       6

In [31]:
df.corr()

/tmp/ipykernel_7099/1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


age  newcol
age     1.0     1.0
newcol  1.0     1.0

In [32]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [33]:
df[~df.duplicated()]

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [34]:
df.isna()

age   name  newcol
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False   False

In [35]:
df.dropna(inplace=True)

In [36]:
df

age   name  newcol
0   11  alice      22
1   21   ange      42
2   31   bebe      62
3   41  alice      82
4   51  olive     102
5   61  alice     122
6   71    def     142
7   81   elie     162

In [37]:
my_array = np.array([2,3,4])
my_array.ndim

1

In [39]:
my_array = np.array([[2,3,4]])
my_array.ndim

2

In [44]:
zoro=np.zeros((3,2))

In [45]:
zoro

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
zoro.ndim

2

In [49]:
my_array = np.array([[[2,3,4]]])
my_array.ndim

3

In [50]:
# we can found ndim as number of dimension for numpy and it is number of brackets

In [53]:
my_array1= np.array([2,3,4])
my_array2= np.array([2,3,4])
np.vstack((my_array1,my_array2))

array([[2, 3, 4],
       [2, 3, 4]])

In [54]:
np.hstack((my_array1,my_array2))#concatinate

array([2, 3, 4, 2, 3, 4])

In [56]:
np.random.randn(2,3).astype('int')

array([[1, 0, 0],
       [0, 1, 0]])